---
- name: creating user
  hosts: all
  become: true
  gather_facts: no
  vars:
    user_name: modi

  tasks:
  - name: creating user {{ user_name }}
    user:
       name: "{{ user_name }}"
       
  - name: create a directory
    file:
       path: /opt/{{ user_name}}_temp_dir
       state: directory
       owner: "{{ user_name }}"
       group: "{{ user_name }}"
       mode: 0755
